# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["you@example.com"]
description = "Fastly Compute static site"
language = "javascript"
manifest_version = 3
name = "lepagejeremi-Maison-Orare"
service_id = "LOo3jx4KDGMFBaaAC5X7iU"

[local_server]

  [local_server.kv_stores]

    [local_server.kv_stores.lepagejeremi-Maison-Orare-content]
      file = "./static-publisher/kvstore.json"
      format = "json"

[scripts]
  build = "npm run build"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.lepagejeremi-Maison-Orare-content]
